### ISSUE TITLE
Property 'gatherer' of type 'string | undefined' is not assignable to string index type 'string'. importing the library in a clean project.

### ISSUE THREAD

**Issue by usersaurus** [Yuudaari/scryfall-sdk#11]
Importing the library in a clean create-react-app ts project is throwing the following error in IScry.d.ts

`Property 'gatherer' of type 'string | undefined' is not assignable to string index type 'string'.`

The same is happening in the following interfaces

`export interface RelatedUris {
  gatherer?: string;
  tcgplayer_decks?: string;
  edhrec?: string;
  mtgtop8?: string;
  [key: string]: string;
}`

`export interface PurchaseUris {
  amazon?: string;
  ebay?: string;
  tcgplayer?: string;
  magiccardmarket?: string;
  cardhoarder?: string;
  card_kingdom?: string;
  mtgo_traders?: string;
  coolstuffinc?: string;
  [key: string]: string;
}`

Removing `?` in all these types fix the problem (and, as far as I know, that info is always populated by scryfall api).

Don't know if I'm missing something. If not, I'm able to PR the change.

**Comment by Yuudaari** [comment]
What version of typescript are you using?

**Comment by usersaurus** [comment]
Oh, sorry. Tried with Typescript 3.1.3 and 3.1.5.

**Comment by usersaurus** [comment]
Not working correctly in 3.1.6 too

**Comment by Yuudaari** [comment]
Should be fixed as of v1.3.3
