### ISSUE TITLE
Implement /cards/collection endpoint

### ISSUE THREAD

**Issue by Joel-Mercier** [Yuudaari/scryfall-sdk#13]
Hi, first off great work ! Your sdk has been really helpful to me ! I was just wondering and I hope I didn't miss it but the /cards/collection endpoint (https://scryfall.com/docs/api/cards/collection) doesn't seem to be implemented. Any plans to support this ? I can get by without it but it would be awesome

**Comment by Yuudaari** [comment]
This wasn't yet a thing last time I did dev on the project. I'll make time to implement this sometime soon, thanks for the ping!

**Comment by Joel-Mercier** [comment]
Hi any news on this ? This endpoint would be very useful for card collections (like decks)

**Comment by Yuudaari** [comment]
It's implemented as of [v1.4.0](https://github.com/Yuudaari/scryfall-sdk/blob/master/CHANGELOG.md)

Sorry about that, I should have made some time before now but I just didn't. It didn't even take long to implement, maybe like 3 hours. I really should have done that sooner 😓

**Comment by Joel-Mercier** [comment]
Awesome ! will test
