### ISSUE TITLE
Use a different network library so the sdk is usable in browser

### ISSUE THREAD

**Issue by somkun** [Yuudaari/scryfall-sdk#17]
The **request** and **request-promise** libraries do not work in the browser, (which is as intended) but it would be easy to replace them with a cross platform solution such as [axios](https://github.com/axios/axios). I've started working on this in a fork for my own use, but I'd love to upstream my change for everyone to enjoy.

**Comment by Yuudaari** [comment]
I think you can make request/request-promise work using webpack but I'm not familiar with a lot of that stuff (most of my dev w/ web technologies is in electron), but axios sounds like it would be easier.

Feel free to PR. I'll tackle switching to it sometime soon if you don't get to it.
