### ISSUE TITLE
Diffrent number of cards

### ISSUE THREAD

**Issue by davidsoderberg** [Yuudaari/scryfall-sdk#2]
Hi when I use `Scryfall.Cards.search('s:' + 'kld').waitForAll().then`, I got 439 cards for result.
But if I use [https://api.scryfall.com/cards/search?q=s:kld](https://api.scryfall.com/cards/search?q=s:kld), I get 264 cards for result. Should they not be the same number? I know I get duplicates and the have the same id from Scryfall. One example is "Key of the city".

**Comment by Yuudaari** [comment]
This sounds like a bug, but I'll have to look into it on my end. My job is a bit busy at the moment, so I'm not sure when I'll get to it. Hopefully within the week. Sorry for the wait!

**Comment by davidsoderberg** [comment]
I have made a reducer on my side to remove duplicates, looking on id from Scryfall. But yea a fix for this would be amazing 😄

**Comment by Yuudaari** [comment]
Fixed as of [v1.0.2](https://www.npmjs.com/package/scryfall-sdk)

Turns out the first page of the scryfall api is `1`, not `0`. Surprised I never noticed this. My tests weren't good enough!!
