### ISSUE TITLE
All Cards api route deprecated

### ISSUE THREAD

**Issue by Juviro** [Yuudaari/scryfall-sdk#31]
The previous route to obtain all cards
`https://api.scryfall.com/cards?page=0`
has been [deprecated ](https://scryfall.com/blog/category/api).

Therefore, `Cards.all` does not work anymore for this api

<img width="361" alt="Bildschirmfoto 2020-06-20 um 21 28 16" src="https://user-images.githubusercontent.com/11948240/85210021-ff3fc380-b33c-11ea-854d-1cd9eedd8284.png">

Any plans to change this to the suggested [Bulk Data endpoints](https://scryfall.com/docs/api/bulk-data)? Any help needed?

**Comment by Yuudaari** [comment]
Ah, didn't see that notice. I'll add support for downloading the bulk data today
