### ISSUE TITLE
MagicEmitter.waitForAll() doesn't work when internal Promises resolves as an error

### ISSUE THREAD

**Issue by Gorefistus** [Yuudaari/scryfall-sdk#4]
It's actually easy to reproduce, just make a strict card search with non-existent card name. For example:

`Scry.Cards.search(`!smoker`).waitForAll()`

 will generate an error than cannot be catched with .catch() method.

**Comment by Yuudaari** [comment]
Fixed as of v1.2.1. Thanks!
