### ISSUE TITLE
Allow setting max query time & retry if time is exceeded

### ISSUE THREAD

**Issue by Yuudaari** [Yuudaari/scryfall-sdk#7]

**Comment by usersaurus** [comment]
I can help if u want. Can u provide a extended info of this enhancement?

**Comment by Yuudaari** [comment]
I'm not sure what all it will entail as I haven't looked into it actually doing it yet. Been busy with other things. It'll probably be faster for me to just write it myself than write up a spec for a PR. I've sorta been waiting for someone else to need this in as a push to implementing it. Nobody seems to have needed it so far tho
