### ISSUE TITLE
Allow queryApi function to return Error Object

### ISSUE THREAD

**Issue by dantolini** [Yuudaari/scryfall-sdk#9]
The Scryfall api provides nice, human readable error messages (https://scryfall.com/docs/api/errors), but these are being swallowed by queryApi, which will return { data: [] } on an error.
By allowing the error object to be returned (or at least retrieved), a program can report to the user problems with the query.

**Comment by Yuudaari** [comment]
Thanks for the report! This is implemented as of [v1.3.1](https://github.com/Yuudaari/scryfall-sdk/blob/master/CHANGELOG.md)
